momentum: 0.0
weight_decay: 0.0
cuda: True
burnin_period: 160
noise_scale:
    grid_search: [0.1, 0.01, 0.001]
# specify absolute path here so u don't download the data for each trial w/ray
dataroot: /Users/noah/Dev/SGLD/data 
